version: 2
jobs:
  build:
    docker:
      - image: node:9.9.0
    working_directory: ~/atxbourbon.com
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
      - run:
          name: cd
          command: cd ./atxbourbon.com 
      - run:
          name: Generate static website
          command: hexo generate
      - run:
          name: Install AWS CLI
          command: |
            apt-get update
            apt-get install -y awscli
      - run:
          name: Push to S3 bucket
          command: cd public/ && aws s3 sync . s3://atxbourbon.com