version: 2
jobs:
  build:
    docker:
      - image: node:9.9.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: cd ./atxbourbon.com && npm install -g hexo-cli
      - run:
          name: Install dependencies
          command: cd ./atxbourbon.com && npm install
      - run:
          name: Generate static website
          command: cd ./atxbourbon.com && hexo generate
      - run:
          name: printenv
          command: printenv
      - run:
          name: Install AWS CLI
          command: |
            apt-get update
            apt-get install -y awscli
      - run:
          name: Push to S3 bucket
          command: cd ./atxbourbon.com/public/ && aws s3 sync . s3://atxbourbon --region us-west-2